### ISSUE TITLE
Location

### ISSUE THREAD

**Issue by Fumesover** [Gibtnix/MSIKLM#11]
Hi,
I installed this pakage directly from the AUR with yaourt and the binary location is /usr/bin/msiklm istead of /usr/locale/bin/msiklm
And so, you'r script install.sh wasn't working to add the start rule !

Can you correct it ? Or add a way to create this file inside of the main binary ?

Txk you for this program ! My keyboard is reborn

**Comment by lhark** [comment]
Hello,

I maintain msiklm-git on the AUR. On archlinux, **install.sh** is of no use to you as the whole installation process is handled by the PKGBUILD. Also **install.sh** uses apt which is the package manager for debian-based systems.

But I think you meant to talk about **autostart.sh** which will create the right udev rule. You could either manually replace **/usr/local/bin/msiklm** by **/usr/bin/msiklm** in the file (lines 19, 24, 29), or go the systemd service route and create **/etc/systemd/system/msiklm.service** like so:
```
[Unit]
Description=Set keyboard backlight parameters

[Service]
Type=oneshot
ExecStart=/usr/bin/msiklm "red,[32;32;255],green"

[Install]
WantedBy=multi-user.target
```
