### ISSUE TITLE
Speed of Wave Mode

### ISSUE THREAD

**Issue by skrish13** [Gibtnix/MSIKLM#2]
Hi, 
I have two feature requests :)

1. Is it possible to reduce the speed of Wave mode? 

2. Also, the standard wave mode in Windows (Steelseries app) look far more good since this current speed is kinda annoying to my eyes. I think it can be done by implementing the slow fading of 'Demo' in Wave mode (of course not to fade completely) to create a new mode maybe?

**Comment by Gibtnix** [comment]
Hi,

first of all thanks for using MSIKLM and your comment! :+1: 

Regarding your questions: I guess that somehow it is possible to control the wave mode's speed (the SteelSeries Engine seems to be able to do this, so theoretically it is), but unluckily I do not know how to do. There is no API documentation available how to communicate with the keyboard, I guess a few folks found out a few ways by reverse engineering and/or trial and error. This means that if there is some more knowledge available how additional features can be implemented, I'd like to integrate them to offer all users the most configuration possibilities. But currently I guess it is not possible to control wave mode's speed or to create new modes. The only way of doing this might be to have an endless running program and change the colors/modes/intensities etc. in certain time steps (e.g. switch from all-red to all-blue to whatever all 10 seconds) but this involves both a) a service that keeps running in the background that uses system resources (but this should be a minor issue) as well as b) that the keyboard receives a new command in the respective time intervals and I do not know if this can be a problem after a certain time running…

I hope this helps a bit :-)

**Comment by skrish13** [comment]
Oh, Okay. Ya, there are other folks who have also made a msi-klm, i had tried one which is based on nodejs, if I remember correctly, even that had the same modes and configurations. Sad that it isn't easily configurable :(. Anyways, thanks for the quick reply :smile:

**Comment by Gibtnix** [comment]
No problem, fell free to ask if there are other issues :smirk:
