### ISSUE TITLE
White backlight whatever i choose.

### ISSUE THREAD

**Issue by Thirtykay** [Gibtnix/MSIKLM#22]
Hello,
I have a MSI GE60 2QE Apache Pro running Manjaro Linux, when i test the connection between the keyboard and the program, everything is ok, but when i try for exemple sudo msiklm green, and this, whatever the color i'm choosing.

Any idea ? 

Thanks.

**Comment by Gibtnix** [comment]
No problem, glad that it's working for you :+1:
