### ISSUE TITLE
Autostart with 2 parameters isn't parsed correctly

### ISSUE THREAD

**Issue by Vuttz** [Gibtnix/MSIKLM#3]
I tried to run:
`./autostart.sh white low`
It gave this error:
`Activating MSIKLM autostart...
low"' >> /etc/udev/rules.d/99-msiklm.rules: 1: low"' >> /etc/udev/rules.d/99-msiklm.rules: Syntax error: Unterminated quoted string`

Then I tried:
`./autostart.sh "white low"` 
It gave me this error:
`./autostart.sh: 15: [: white: unexpected operator`

The workaround was to use only one parameter: white, and then edit the generated file and add the second paramenter: low.

Thank you for creating this great tool as it is easily the best of the 3 I found.

**Comment by Gibtnix** [comment]
Hi,

thanks for your comment! It seems as I actually never tested the autostart functionality for more than one argument; however I just updated the autostart script accordingly, i.e. all kinds of autostart arguments should be possible now. I also updated a few C functions, but these are rather minor issues. Please try the latest version and let me know if there are still some problems, but there should not be any :-)
