### ISSUE TITLE
MSI alpha 15 - No compatible keyboard found!

### ISSUE THREAD

**Issue by gerardo-pivotto-santex** [Gibtnix/MSIKLM#37]
Hello, I'm trying to use your application it seems to be really great. But In my case in ubuntu 20.04 is not recognizing me the keyboard. When I run msiklm list the output:
Device: SteelSeries KLC
    Device Vendor ID:        4152
    Device Product ID:       4386
    Device Serial Number:    (null)
    Device Manufacturer:     SteelSeries
    Device Path:             0003:0004:00
    Device Interface Number: 0
    Device Release Number:   560

Device: SteelSeries KLC
    Device Vendor ID:        4152
    Device Product ID:       4386
    Device Serial Number:    (null)
    Device Manufacturer:     SteelSeries
    Device Path:             0003:0004:01
    Device Interface Number: 1
    Device Release Number:   560
If you could point me to the right direction I may create a pull request to resolve this.

Regards,
Gerardo

**Comment by Gibtnix** [comment]
Hello,

well, I don't know if your keyboard's controller is supported or not. To test, you will need to modify the open_keyboard() function in msiklm.c according to the IDs that are given by list. Doing so and recompiling the program will find your keyboard by using `msiklm test`. Still, it is unclear if any of the commands are working. However, you can try out whatever you want once it is detected. Maybe also the command structure (cf. set_color() and set_mode() functions in msiklm.c) needs to be adjusted accordingly. If you find a solution I'm open towards any PR extending the functionality. Good luck :+1:

**Comment by gerardo-pivotto-santex** [comment]
I was able to make the program 1038:1122 SteelSeries ApS USB2.0 Hub
$> grep hid_open src/msiklm.c 
dev = hid_open(0x1038, 0x1122, 0);
$> sudo ./msiklm test
Compatible keyboard found!

But I's not recognizing the command. I'll need to find the proper code for that!

Thanks for the quick reply. If I'm able to fix this I'll get in touch to review how this could be merge into the actual solution.

Regards,
G

**Comment by Gibtnix** [comment]
You're welcome, appreciating any extension of the current functionality as long as it does not break some of the current functions, i.e. backward compatibility should be kept. If you find a solution, it might be possible to integrate your keyboard by testing both IDs and maybe save a flag which one actually is used. Then, set_color() and set_mode() could be extended accordingly. Maybe it might be possible to analyze the command structures using a tool like Wireshark on Windows.
