### ISSUE TITLE
Unable to set logo color to "blue"

### ISSUE THREAD

**Issue by meeces2911** [Gibtnix/MSIKLM#5]
I haven't got round to debugging this yet (only have a minute or 2 to log the issue), but for whatever reason entering "sudo msiklm blue,green,red,blue,red,red,blue" results in a Invalid argument error. But choosing, say, white or red, to the logo value works successfully *sudo msiklm blue,green,red,red,red,red,blue".

Setting the logo color to [0;0;255] also works successfully.

**Comment by Gibtnix** [comment]
Thanks for reporting the issue! I just took a look at it and it seems to be something strange... Just printing the the current color value seems to fix the issue while the remaining part stays the same (i.e. just insert 'printf("color_str = %s\n", color_str);' as the first statement of the color parsing while loop) seems to fix the issue. I'll try to find out what's going wrong here...

**Comment by Gibtnix** [comment]
I found the error's source, please try the current version and please give me some feedback if it is now properly working for you :-)

**Comment by meeces2911** [comment]
Thanks, it seems to be working great!
