### ISSUE TITLE
No Compatible Keyboard found | MSI GL66 laptop

### ISSUE THREAD

**Issue by Volodya-B1tik** [Gibtnix/MSIKLM#51]
Is there no support for MSI GL66 laptop, or did I do something wrong?

`sudo msiklm list`

> Device: MysticLight MS-1563 v0001
>     Device Vendor ID:        5218
>     Device Product ID:       5475
>     Device Serial Number:    207438935942
>     Device Manufacturer:     MSI
>     Device Path:             0003:0003:00
>     Device Interface Number: 0
>     Device Release Number:   512
`
sudo msiklm test`

> result:
> 
> No compatible keyboard found!
> Check you're using sudo!

**Comment by Gibtnix** [comment]
I just added a device support section to the readme because similar questions were asked multiple times and I thought it might be helpful to add my comments directly there. Please refer to these and feel free to ask again if there remains something unclear.
